FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk git maven && \
    apt-get clean

WORKDIR /app


RUN git clone https://github.com/dockersamples/spring-petelinic-docker.git

WORKDIR /app/spring-petclinic-docker

RUN ./mvnw package

EXPORT 8080

EVN APP_VERSION="1.0.0"

RUN echo "Running Spring Petclinic version $APP_VERSION"

HEALTHCHCK --interval=20s --timeout-10s \
cmd curl -f htt://localhost:8080 || exit 1
CMD ["java", "-jar", "target/spring-petclinic*.jar"]
